# Generated by Django 5.1.5 on 2025-02-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_adress',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='user_adress',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='users',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='users',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
